#!/bin/bash
if [ ! -f /saltyrtc/certs/saltyrtc.crt ]; then
    echo 'Certificate not found. Please run `generate-cert.sh` first.'
    exit 1
fi

set -x
saltyrtc-server \
    -v 6 \
    serve \
    -sc /saltyrtc/certs/saltyrtc.crt \
    -sk /saltyrtc/certs/saltyrtc.key \
    -p 8765 \
    -k $SALTYRTC_SERVER_PERMANENT_KEY > /saltyrtc/serverlog.txt 2>&1 &
echo $!
