version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Debug information
          command: 'echo -e "Circle branch: ${CIRCLE_BRANCH}\nDocker login: ${DOCKER_LOGIN}"'
      - run:
          name: Build Docker image
          command: |
            docker build \
              --no-cache \
              -t saltyrtc/circleci-image-rs:latest \
              -t saltyrtc/circleci-image-rs:1.47 \
              -t saltyrtc/circleci-image-rs:${CIRCLE_BRANCH} \
              .
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_ACCESS_TOKEN && \
            docker push saltyrtc/circleci-image-rs

workflows:
  version: 2

  # Build on push to master
  on_push:
    jobs:
      - build:
          context: Docker Hub Upload
          filters:
            branches:
              only:
                - master

  # Build every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: Docker Hub Upload
