version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build \
              -t saltyrtc/circleci-image-rs:latest \
              -t saltyrtc/circleci-image-rs:${CIRCLE_BRANCH}
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_EMAIL -p $DOCKER_API_KEY && \
            docker push saltyrtc/circleci-image-rs

